services:
  - type: web
    name: portfolio
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: GOOGLE_GEMINI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
    autoDeploy: true
